services:
  wave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wave
    image: wave
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
